default: &default
  adapter: postgresql
  encoding: utf8
  user: khuramdogar
  password: 12345
  host: localhost
  database: puls_development
production:
  <<: *default
development:
  <<: *default
  database: puls_development